### ISSUE TITLE
2. k8s 환경 구성 용도의 cloud-init 추가

### ISSUE THREAD

**Issue by TLOWAC** [TLOWAC/cloud-init-config#2]

**Comment by TLOWAC** [comment]
```yaml
#cloud-config
write_files:
  - path: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  - path: /etc/security/limits.d/kubernetes.conf
    content: |
      * soft nofile 65536
      * hard nofile 65536
      * soft nproc 65536
      * hard nproc 65536
runcmd:
  - curl https://get.docker.com | bash
  - systemctl enable docker
  - systemctl start docker
  - setenforce 0
  - yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
  - systemctl enable kubelet
  - systemctl start kubelet
  - kubeadm init --pod-network-cidr=192.168.0.0/16
  - mkdir -p $HOME/.kube
  - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  - chown $(id -u):$(id -g) $HOME/.kube/config
  - kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
```
